# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbb4eb4c2949829d954636f5967090068a787aed8af6d2b263b4835e195d9e469e2a6167139c5161e12461a5a6b1fb1972d1cb72f59d2d19f90da30f22511c29

test:
  secret_key_base: 20168e54fc15c3e50b6a4b0e9299d63149b00ca42ef5c7f5ff1b8f9d2db0eb2ef2e0e47039d11e7f1af235bc392ff9756fda0c00f40c1369ee7d96698cca1623

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
